# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: mercari/appengine-go:1.11

    working_directory: /go/src/deep-track-staging
    steps:
      - checkout

      # Test related should be inserted here

      - run:
          name: install go dep
          command: mkdir -p /go/bin && curl -sL https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 > /go/bin/dep && chmod +x /go/bin/dep

      - run:
          name: decrypt keys
          command: make decrypt

      - run:
          name: fix goapp command
          command: |
            if [ ! -e /usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/goroots.py ]; then
             echo "Writing goroots.py"
             echo "GOROOTS = {'go1': 'goroot-1.11','go1.6': 'goroot-1.6','go1.8': 'goroot-1.8',}" > /usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/goroots.py
            fi

      - deploy:
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=`pwd`/.secret/secret-key.json
            gcloud auth activate-service-account --key-file ./.secret/secret-key.json
            appcfg.py update --no_cookies --oauth2_access_token $(gcloud auth print-access-token 2> /dev/null) -A $GCLOUD_PROJECT -V ./app/
            gcloud config set project $GCLOUD_PROJECT
